[package]
name = "gabe"
version = "0.1.0"
authors = ["Joe Thill <rocketlobster42@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[dependencies]
clap = "2.33.0"
log = "*"
env_logger = "*"
minifb = "0.23.0"
spin_sleep = "1.1.1"
blip_buf = "0.1.4"