[package]
name = "gabe_core"
version = "0.1.0"
authors = ["Joe Thill <rocketlobster42@gmail.com>"]
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[dependencies]
log = "*"